name: simple_dart_object_table
description: Object Table Component
version: 0.0.2
repository: https://github.com/simple-dart/object_table
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_checkbox: ^0.0.1
  simple_dart_table: ^0.0.4
  simple_dart_ui_core: ^0.0.2
